"use client";

import type { ReactNode } from "react";
import { Brain, FileText, Sparkles, Clock, TrendingUp, TrendingDown, AlertTriangle } from "lucide-react";
import Header from "../components/Header";
import Metric from "../components/Metric";
import Reveal, { RevealStagger, RevealItem } from "../components/Reveal";
import { PREDICTIVE_INSIGHTS, HEALTH_TREND, MODEL_METRICS } from "../lib/insights";
import { CATEGORIES, DOCUMENTS } from "../lib/documents";
import { useLanguage } from "../lib/LanguageContext";
import { STATUS_LABELS, CATEGORY_LABELS } from "../lib/translations";
import { cardBase, cardStatic } from "../lib/ui";

const TREND_STYLES: Record<string, { icon: ReactNode; badge: string }> = {
  up: { icon: <TrendingUp size={18} />, badge: "text-success-700 bg-success-100" },
  down: { icon: <TrendingDown size={18} />, badge: "text-danger-700 bg-danger-100" },
  warning: { icon: <AlertTriangle size={18} />, badge: "text-warning-700 bg-warning-100" },
};

const INSIGHTS_TEXT = {
  en: {
    tag: "PREDICTIVE INTELLIGENCE",
    title: "AI Insights",
    subtitle: "Portfolio-wide trends, predictive risk signals, and model performance generated by the AI platform.",
    aiAccuracy: "AI Accuracy",
    documentsProcessed: "Documents Processed",
    activePredictions: "Active Predictions",
    avgProcessingTime: "Avg. Processing Time",
    healthTrend: "Portfolio Health Trend",
    modelPerformance: "Model Performance",
    predictiveInsights: "Predictive Insights",
    confidence: "confidence",
    docsByCategory: "Documents Processed by Category",
    total: "total",
  },
  fr: {
    tag: "INTELLIGENCE PRÉDICTIVE",
    title: "Analyses IA",
    subtitle: "Tendances à l'échelle du portefeuille, signaux de risque prédictifs et performance des modèles générés par la plateforme IA.",
    aiAccuracy: "Précision de l'IA",
    documentsProcessed: "Documents Traités",
    activePredictions: "Prédictions Actives",
    avgProcessingTime: "Temps de Traitement Moyen",
    healthTrend: "Tendance de Santé du Portefeuille",
    modelPerformance: "Performance du Modèle",
    predictiveInsights: "Analyses Prédictives",
    confidence: "confiance",
    docsByCategory: "Documents Traités par Catégorie",
    total: "au total",
  },
};

export default function Insights() {
  const { lang } = useLanguage();
  const t = INSIGHTS_TEXT[lang];
  const statusLabels = STATUS_LABELS[lang];
  const categoryLabels = CATEGORY_LABELS[lang];

  const docsByCategory = CATEGORIES.map((category) => ({
    category,
    count: DOCUMENTS.filter((d) => d.category === category).length,
  })).sort((a, b) => b.count - a.count);

  const maxDocsCount = Math.max(...docsByCategory.map((d) => d.count));

  return (
    <main className="min-h-screen bg-[#f4f9ff] text-slate-950">
      <Header active="Insights" />

      <section className="max-w-7xl mx-auto px-8 pt-14 pb-6">
        <Reveal>
          <p className="text-primary-600 font-bold">{t.tag}</p>
          <h1 className="text-4xl font-extrabold mt-2 font-display">{t.title}</h1>
          <p className="mt-3 text-slate-700 max-w-2xl">{t.subtitle}</p>
        </Reveal>
      </section>

      <section className="max-w-7xl mx-auto px-8">
        <RevealStagger className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          <RevealItem>
            <Metric icon={<Brain />} title={t.aiAccuracy} value="95%" />
          </RevealItem>
          <RevealItem>
            <Metric icon={<FileText />} title={t.documentsProcessed} value={String(DOCUMENTS.length)} />
          </RevealItem>
          <RevealItem>
            <Metric icon={<Sparkles />} title={t.activePredictions} value={String(PREDICTIVE_INSIGHTS.length)} />
          </RevealItem>
          <RevealItem>
            <Metric icon={<Clock />} title={t.avgProcessingTime} value="4.2s" />
          </RevealItem>
        </RevealStagger>
      </section>

      <section className="max-w-7xl mx-auto px-8 py-12 grid grid-cols-1 xl:grid-cols-3 gap-8">
        <Reveal className={`xl:col-span-2 ${cardBase} p-8`}>
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold">{t.healthTrend}</h2>
            <div className="flex items-center gap-4 text-xs font-semibold text-slate-500">
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-success-500" /> {statusLabels["On Track"]}
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-warning-400" /> {statusLabels["At Risk"]}
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-danger-500" /> {statusLabels.Delayed}
              </span>
            </div>
          </div>

          <div className="h-48 flex items-end justify-between gap-6 px-2">
            {HEALTH_TREND.map((m) => (
              <div key={m.month} className="flex flex-col items-center gap-2 flex-1">
                <div className="w-full max-w-10 h-40 rounded-xl overflow-hidden flex flex-col bg-primary-50">
                  <div style={{ height: `${m.onTrack}%` }} className="bg-success-500 transition-[height] duration-700 ease-out" />
                  <div style={{ height: `${m.atRisk}%` }} className="bg-warning-400 transition-[height] duration-700 ease-out" />
                  <div style={{ height: `${m.delayed}%` }} className="bg-danger-500 transition-[height] duration-700 ease-out" />
                </div>
                <span className="text-xs font-semibold text-slate-500">{m.month}</span>
              </div>
            ))}
          </div>
        </Reveal>

        <Reveal delay={0.1} className={`${cardBase} p-8`}>
          <h2 className="text-xl font-bold mb-6">{t.modelPerformance}</h2>

          <div className="space-y-5">
            {MODEL_METRICS.map((metric) => (
              <div key={metric.label}>
                <div className="flex items-center justify-between text-sm">
                  <span className="font-semibold text-slate-700">{metric.label}</span>
                  <span className="font-bold">{metric.value}</span>
                </div>
                {metric.percent !== undefined && (
                  <div className="mt-2 h-2 bg-primary-50 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-primary-600 rounded-full transition-[width] duration-700 ease-out"
                      style={{ width: `${metric.percent}%` }}
                    />
                  </div>
                )}
              </div>
            ))}
          </div>
        </Reveal>
      </section>

      <section className="max-w-7xl mx-auto px-8 pb-12">
        <h2 className="text-xl font-bold mb-6">{t.predictiveInsights}</h2>

        <RevealStagger className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {PREDICTIVE_INSIGHTS.map((insight) => (
            <RevealItem key={insight.id} className={`${cardBase} p-6`}>
              <div className="flex items-start justify-between gap-4">
                <div className={`w-11 h-11 rounded-2xl flex items-center justify-center shrink-0 ${TREND_STYLES[insight.trend].badge}`}>
                  {TREND_STYLES[insight.trend].icon}
                </div>
                <span className="text-xs font-bold text-slate-500 bg-slate-100 px-3 py-1 rounded-full whitespace-nowrap">
                  {insight.confidence}% {t.confidence}
                </span>
              </div>

              <h3 className="font-bold mt-4">{insight.title}</h3>
              <p className="text-sm text-slate-600 mt-2">{insight.description}</p>
              <p className="text-xs font-semibold text-primary-600 mt-4">{insight.program}</p>
            </RevealItem>
          ))}
        </RevealStagger>
      </section>

      <section className="max-w-7xl mx-auto px-8 pb-20">
        <Reveal className={`${cardStatic} p-8`}>
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold">{t.docsByCategory}</h2>
            <span className="text-sm text-slate-500 font-semibold">{DOCUMENTS.length} {t.total}</span>
          </div>

          <div className="space-y-4">
            {docsByCategory.map((row) => (
              <div key={row.category} className="flex items-center gap-4">
                <span className="text-sm font-semibold text-slate-700 w-56 shrink-0">
                  {categoryLabels[row.category]}
                </span>
                <div className="flex-1 h-2.5 bg-primary-50 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-primary-600 rounded-full transition-[width] duration-700 ease-out"
                    style={{ width: `${(row.count / maxDocsCount) * 100}%` }}
                  />
                </div>
                <span className="text-sm font-bold text-slate-700 w-6 text-right">{row.count}</span>
              </div>
            ))}
          </div>
        </Reveal>
      </section>
    </main>
  );
}
