import type { ReactNode } from "react";
import { Brain, FileText, Sparkles, Clock, TrendingUp, TrendingDown, AlertTriangle } from "lucide-react";
import Header from "../components/Header";
import Metric from "../components/Metric";
import { PREDICTIVE_INSIGHTS, HEALTH_TREND, MODEL_METRICS } from "../lib/insights";
import { CATEGORIES, DOCUMENTS } from "../lib/documents";

const TREND_STYLES: Record<string, { icon: ReactNode; badge: string }> = {
  up: { icon: <TrendingUp size={18} />, badge: "text-emerald-700 bg-emerald-100" },
  down: { icon: <TrendingDown size={18} />, badge: "text-rose-700 bg-rose-100" },
  warning: { icon: <AlertTriangle size={18} />, badge: "text-amber-700 bg-amber-100" },
};

export default function Insights() {
  const docsByCategory = CATEGORIES.map((category) => ({
    category,
    count: DOCUMENTS.filter((d) => d.category === category).length,
  })).sort((a, b) => b.count - a.count);

  const maxDocsCount = Math.max(...docsByCategory.map((d) => d.count));

  return (
    <main className="min-h-screen bg-[#f4f9ff] text-slate-950">
      <Header active="Insights" />

      <section className="max-w-7xl mx-auto px-8 pt-14 pb-6">
        <p className="text-blue-600 font-bold">PREDICTIVE INTELLIGENCE</p>
        <h1 className="text-4xl font-extrabold mt-2">AI Insights</h1>
        <p className="mt-3 text-slate-700 max-w-2xl">
          Portfolio-wide trends, predictive risk signals, and model
          performance generated by the AI platform.
        </p>
      </section>

      <section className="max-w-7xl mx-auto px-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          <Metric icon={<Brain />} title="AI Accuracy" value="95%" />
          <Metric icon={<FileText />} title="Documents Processed" value={String(DOCUMENTS.length)} />
          <Metric icon={<Sparkles />} title="Active Predictions" value={String(PREDICTIVE_INSIGHTS.length)} />
          <Metric icon={<Clock />} title="Avg. Processing Time" value="4.2s" />
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-8 py-12 grid grid-cols-1 xl:grid-cols-3 gap-8">
        <div className="xl:col-span-2 bg-white rounded-3xl p-8 shadow-xl border border-blue-100">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold">Portfolio Health Trend</h2>
            <div className="flex items-center gap-4 text-xs font-semibold text-slate-500">
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" /> On Track
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-amber-400" /> At Risk
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500" /> Delayed
              </span>
            </div>
          </div>

          <div className="h-48 flex items-end justify-between gap-6 px-2">
            {HEALTH_TREND.map((m) => (
              <div key={m.month} className="flex flex-col items-center gap-2 flex-1">
                <div className="w-full max-w-10 h-40 rounded-xl overflow-hidden flex flex-col bg-blue-50">
                  <div style={{ height: `${m.onTrack}%` }} className="bg-emerald-500" />
                  <div style={{ height: `${m.atRisk}%` }} className="bg-amber-400" />
                  <div style={{ height: `${m.delayed}%` }} className="bg-rose-500" />
                </div>
                <span className="text-xs font-semibold text-slate-500">{m.month}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-3xl p-8 shadow-xl border border-blue-100">
          <h2 className="text-xl font-bold mb-6">Model Performance</h2>

          <div className="space-y-5">
            {MODEL_METRICS.map((metric) => (
              <div key={metric.label}>
                <div className="flex items-center justify-between text-sm">
                  <span className="font-semibold text-slate-700">{metric.label}</span>
                  <span className="font-bold">{metric.value}</span>
                </div>
                {metric.percent !== undefined && (
                  <div className="mt-2 h-2 bg-blue-50 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-blue-600 rounded-full"
                      style={{ width: `${metric.percent}%` }}
                    />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-8 pb-12">
        <h2 className="text-xl font-bold mb-6">Predictive Insights</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {PREDICTIVE_INSIGHTS.map((insight) => (
            <div
              key={insight.id}
              className="bg-white rounded-3xl p-6 shadow-xl border border-blue-100"
            >
              <div className="flex items-start justify-between gap-4">
                <div className={`w-11 h-11 rounded-2xl flex items-center justify-center shrink-0 ${TREND_STYLES[insight.trend].badge}`}>
                  {TREND_STYLES[insight.trend].icon}
                </div>
                <span className="text-xs font-bold text-slate-500 bg-slate-100 px-3 py-1 rounded-full whitespace-nowrap">
                  {insight.confidence}% confidence
                </span>
              </div>

              <h3 className="font-bold mt-4">{insight.title}</h3>
              <p className="text-sm text-slate-600 mt-2">{insight.description}</p>
              <p className="text-xs font-semibold text-blue-600 mt-4">{insight.program}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-8 pb-20">
        <div className="bg-white rounded-3xl p-8 shadow-xl border border-blue-100">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold">Documents Processed by Category</h2>
            <span className="text-sm text-slate-500 font-semibold">{DOCUMENTS.length} total</span>
          </div>

          <div className="space-y-4">
            {docsByCategory.map((row) => (
              <div key={row.category} className="flex items-center gap-4">
                <span className="text-sm font-semibold text-slate-700 w-56 shrink-0">
                  {row.category}
                </span>
                <div className="flex-1 h-2.5 bg-blue-50 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-600 rounded-full"
                    style={{ width: `${(row.count / maxDocsCount) * 100}%` }}
                  />
                </div>
                <span className="text-sm font-bold text-slate-700 w-6 text-right">{row.count}</span>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
