export type DocStatus = "Processing" | "Processed";

export type DocumentItem = {
  id: string;
  name: string;
  category: string;
  extension: string;
  size: string;
  uploadedBy: string;
  date: string;
  status: DocStatus;
  summary: string;
};

export const CATEGORIES = [
  "Weekly Status Reports",
  "Architecture & Design",
  "Meeting Notes",
  "Requirements & Specifications",
  "Contracts & Legal",
  "RAID Logs & Risk Registers",
  "Financial Reports",
  "Compliance & Audit",
  "Presentations",
  "Structured Datasets",
] as const;

export const DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-1",
    name: "Program Status Report – Week 27.pdf",
    category: "Weekly Status Reports",
    extension: "pdf",
    size: "1.8 MB",
    uploadedBy: "A. Sidibe",
    date: "Jun 30, 2026",
    status: "Processed",
    summary: "Portfolio health steady; 2 programs flagged at risk due to vendor delays.",
  },
  {
    id: "doc-2",
    name: "Cloud Migration Weekly Update.docx",
    category: "Weekly Status Reports",
    extension: "docx",
    size: "640 KB",
    uploadedBy: "J. Diallo",
    date: "Jun 28, 2026",
    status: "Processed",
    summary: "Cutover rescheduled by two weeks pending vendor infrastructure delivery.",
  },
  {
    id: "doc-3",
    name: "Cloud Migration Target Architecture.pdf",
    category: "Architecture & Design",
    extension: "pdf",
    size: "3.2 MB",
    uploadedBy: "J. Diallo",
    date: "Jun 12, 2026",
    status: "Processed",
    summary: "Defines hybrid cloud topology, network segmentation, and failover strategy.",
  },
  {
    id: "doc-4",
    name: "AI Document Pipeline Design.pptx",
    category: "Architecture & Design",
    extension: "pptx",
    size: "5.1 MB",
    uploadedBy: "M. Traore",
    date: "May 30, 2026",
    status: "Processed",
    summary: "NLP/OCR/RAG ingestion pipeline architecture with model routing diagram.",
  },
  {
    id: "doc-5",
    name: "Steering Committee Notes – Jun 25.docx",
    category: "Meeting Notes",
    extension: "docx",
    size: "210 KB",
    uploadedBy: "A. Sidibe",
    date: "Jun 25, 2026",
    status: "Processed",
    summary: "Approved budget reallocation for Cybersecurity Compliance Audit remediation.",
  },
  {
    id: "doc-6",
    name: "Risk Review Sync Notes.txt",
    category: "Meeting Notes",
    extension: "txt",
    size: "48 KB",
    uploadedBy: "F. Keita",
    date: "Jun 20, 2026",
    status: "Processed",
    summary: "Discussed mitigation plan for site safety monitoring rollout delay.",
  },
  {
    id: "doc-7",
    name: "AI Document Intelligence – Functional Requirements.docx",
    category: "Requirements & Specifications",
    extension: "docx",
    size: "920 KB",
    uploadedBy: "M. Traore",
    date: "May 15, 2026",
    status: "Processed",
    summary: "Specifies intake classification, entity extraction, and retention requirements.",
  },
  {
    id: "doc-8",
    name: "API Integration Spec v2.json",
    category: "Requirements & Specifications",
    extension: "json",
    size: "76 KB",
    uploadedBy: "J. Diallo",
    date: "May 10, 2026",
    status: "Processed",
    summary: "Defines REST endpoints, auth flow, and payload schemas for platform integration.",
  },
  {
    id: "doc-9",
    name: "Cloud Vendor MSA.pdf",
    category: "Contracts & Legal",
    extension: "pdf",
    size: "1.1 MB",
    uploadedBy: "S. Toure",
    date: "Apr 22, 2026",
    status: "Processed",
    summary: "Master service agreement covering SLAs, liability caps, and termination terms.",
  },
  {
    id: "doc-10",
    name: "Data Processing Agreement.pdf",
    category: "Contracts & Legal",
    extension: "pdf",
    size: "540 KB",
    uploadedBy: "S. Toure",
    date: "Apr 18, 2026",
    status: "Processed",
    summary: "Outlines data handling and cross-border transfer obligations with vendor.",
  },
  {
    id: "doc-11",
    name: "Portfolio RAID Log – Q3.xlsx",
    category: "RAID Logs & Risk Registers",
    extension: "xlsx",
    size: "310 KB",
    uploadedBy: "A. Sidibe",
    date: "Jun 29, 2026",
    status: "Processed",
    summary: "18 active risks tracked; 4 high-severity items require executive escalation.",
  },
  {
    id: "doc-12",
    name: "Cybersecurity Risk Register.csv",
    category: "RAID Logs & Risk Registers",
    extension: "csv",
    size: "88 KB",
    uploadedBy: "F. Keita",
    date: "Jun 22, 2026",
    status: "Processed",
    summary: "Tracks regulatory and infrastructure risks tied to the compliance audit program.",
  },
  {
    id: "doc-13",
    name: "Program Budget Variance Report.xlsx",
    category: "Financial Reports",
    extension: "xlsx",
    size: "410 KB",
    uploadedBy: "N. Camara",
    date: "Jun 15, 2026",
    status: "Processed",
    summary: "Portfolio tracking 6% under budget; two programs trending over forecast.",
  },
  {
    id: "doc-14",
    name: "Q2 Cost Forecast.csv",
    category: "Financial Reports",
    extension: "csv",
    size: "64 KB",
    uploadedBy: "N. Camara",
    date: "Jun 1, 2026",
    status: "Processed",
    summary: "Projects Q3 spend across cloud, staffing, and vendor line items.",
  },
  {
    id: "doc-15",
    name: "SOC 2 Readiness Audit.pdf",
    category: "Compliance & Audit",
    extension: "pdf",
    size: "2.4 MB",
    uploadedBy: "F. Keita",
    date: "May 28, 2026",
    status: "Processed",
    summary: "Identifies 5 control gaps to close ahead of Type II certification window.",
  },
  {
    id: "doc-16",
    name: "Regulatory Compliance Checklist.xlsx",
    category: "Compliance & Audit",
    extension: "xlsx",
    size: "150 KB",
    uploadedBy: "F. Keita",
    date: "May 20, 2026",
    status: "Processed",
    summary: "Tracks completion status across 42 regulatory controls by jurisdiction.",
  },
  {
    id: "doc-17",
    name: "Executive Portfolio Review.pptx",
    category: "Presentations",
    extension: "pptx",
    size: "6.7 MB",
    uploadedBy: "A. Sidibe",
    date: "Jun 26, 2026",
    status: "Processed",
    summary: "Board-level summary of portfolio health, spend, and strategic risks.",
  },
  {
    id: "doc-18",
    name: "AI Platform Roadmap.pptx",
    category: "Presentations",
    extension: "pptx",
    size: "4.3 MB",
    uploadedBy: "M. Traore",
    date: "Jun 5, 2026",
    status: "Processed",
    summary: "Outlines H2 2026 roadmap for document intelligence and predictive insights.",
  },
  {
    id: "doc-19",
    name: "Program Metrics Dataset.json",
    category: "Structured Datasets",
    extension: "json",
    size: "22 KB",
    uploadedBy: "J. Diallo",
    date: "Jun 27, 2026",
    status: "Processed",
    summary: "Structured export of program KPIs used to power dashboard metrics.",
  },
  {
    id: "doc-20",
    name: "Risk Scoring Model Inputs.csv",
    category: "Structured Datasets",
    extension: "csv",
    size: "37 KB",
    uploadedBy: "M. Traore",
    date: "Jun 18, 2026",
    status: "Processed",
    summary: "Feature set feeding the predictive risk-scoring model for active programs.",
  },
];
